### ISSUE TITLE
not work on Heroku

### ISSUE THREAD

**Issue by dariomadeira** [davidgatti/How-to-Stream-Torrents-using-NodeJS#6]
I have tried to do the installation in heroku, but it shows an error in

 bufferutil@4.0.3 install /tmp/build_beb57d8d/node_modules/bufferutil
remote:        > node-gyp-build
remote:
remote:        make: Entering directory '/tmp/build_beb57d8d/node_modules/bufferutil/build'
remote:          CC(target) Release/obj.target/bufferutil/src/bufferutil.o
remote:        ../src/bufferutil.c:3:10: fatal error: node_api.h: No such file or directory
remote:            3 | #include <node_api.h>

I don't know how I can fix this, could you help me?

**Comment by davidgatti** [comment]
This is an super old project as a demo, was not designed to work forever, it was designed to help people understand how understand the possibilities of this module.
